# types.py
# types for the ghostwatcher project

from typing import *
from pydantic import BaseModel, Field
from enum import StrEnum

class ExtractionStrategy(StrEnum):
    keyframes = "keyframes"
    interval = "interval"

class ImageExtractorConfig(BaseModel):
    """Config object containing parameters for various extraction functions.
    Not all of the options may be used by all of the functions"""

    use_keyframes: bool = Field(
        default = True,
        description = "Use keyframes or iframes if available in the video."
    )

    min_interval: Optional[float] = Field(
        default = None,
        description = "Minimum interval in seconds between images."
    )

    max_interval: Optional[float] = Field(
        default = None,
        description = "Maximum interval in seconds between images."
    )

    # more options to come in the future
    
class ImageExtractor(Protocol):
    """Interface for video image extractor functions."""

    def process(self, video_filepath: str, output_directory_filepath: str, config: ImageExtractorConfig) -> None:
        pass



class FrameImage(BaseModel):
    """Small wrapper to represent a single video frame, with possible metadata and descriptions."""

    filepath: str = Field(
        description = "The filepath to this frame's image file."
    )
    
    description: Optional[str] = Field(
        default = None,
        description = "An image description generated by a multimodal AI. May built upon descriptions of preceding images."
    )

class FrameCollection(BaseModel):
    """An ordered collection of image frames, with possible descriptions and metadata."""
    video_filepath: str = Field(
        description = "Filepath to the video that the frames belong to. Mostly for logging and documentation purposes."
    )
    
    frames: List[FrameImage] = Field(
        default_factory = list,
        description = "The frames, in chronological order, that were extracted from the video."
    )


